spring.application.name=sodimac
spring.datasource.url=jdbc:mysql://localhost:3306/sodimac
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alexander.cipriano2019@gmail.com
spring.mail.password=liibduqxqdblkrjt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.main.allow-bean-definition-overriding=true